import {checkinPage,bindCheckin} from './checkin.js';
import {invitePage,bindInvite} from './invite.js';
import {applicationPage,bindApplication,resetApplication} from './creator-application.js';
import { anchorIdOf } from './anchor.js';
import {getAuthUser, updateAuthUser, switchMockUser} from './auth.js';
import './account.css';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=[['profile','个人资料','♙'],['spending','消费记录','▤'],['tasks','任务中心','☑'],['checkin','每日签到','▦'],['invite','邀请好友','♧'],['gifts','活动礼包','◇'],['following','我的关注','♡'],['creator','申请主播','♧'],['history','观看历史','◷']];
const seeds=[{name:'发送弹幕',desc:'发送 1 条直播弹幕',current:1,total:1,coins:50,status:'ready'},{name:'观看直播',desc:'观看任意直播 30 秒',current:12,total:30,exp:20,status:'todo'},{name:'订阅主播',desc:'关注 / 订阅 1 位主播',current:1,total:1,diamonds:10,status:'claimed'}];
const ledgers=new Map();
let rewardTab='list',dialog=null,previousFocus=null,codeDeadline=0,codeSent=false,codeTimer=null;
function ledger(){let key=getAuthUser()?.isCreator?'creator':'regular';if(!ledgers.has(key)){let stored;try{stored=JSON.parse(localStorage.getItem('shenma-account-'+key)||'null')}catch{}ledgers.set(key,Array.isArray(stored?.tasks)&&Array.isArray(stored?.records)?{...stored,tasks:stored.tasks.filter(t=>t.name!=='连续签到')}:{tasks:seeds.map(t=>({...t})),records:[{source:'订阅主播任务',reward:'+10 钻石',time:'2026-10-06 10:30'}]})};return ledgers.get(key)}
const saveLedger=()=>localStorage.setItem('shenma-account-'+(getAuthUser()?.isCreator?'creator':'regular'),JSON.stringify(ledger()));
function settleTaskRewards(){
  const data=ledger();
  const completed=data.tasks.filter(t=>t.current>=t.total&&t.status!=='claimed'&&t.status!=='completed');
  if(!completed.length)return;
  const u=getAuthUser();
  updateAuthUser({coins:u.coins+completed.reduce((sum,t)=>sum+(t.coins||0),0),diamonds:u.diamonds+completed.reduce((sum,t)=>sum+(t.diamonds||0),0),exp:u.exp+completed.reduce((sum,t)=>sum+(t.exp||0),0)});
  completed.forEach(t=>{t.status='completed';data.records.unshift({source:t.name+'任务',reward:reward(t),time:new Date().toLocaleString('sv-SE',{timeZone:'Asia/Kuala_Lumpur'}).slice(0,16)})});
  saveLedger();
}
const maskedPhone=()=>{const phone=getAuthUser()?.phone;return phone&&/^\d{11}$/.test(phone)?phone.slice(0,3)+'****'+phone.slice(-4):'暂未绑定手机号'};
const reward=t=>[t.coins?`+${t.coins} 金币`:'',t.diamonds?`+${t.diamonds} 钻石`:'',t.exp?`+${t.exp} 经验值`:''].filter(Boolean).join(' · ');
const activeTab=()=>{let t=new URLSearchParams(location.hash.split('?')[1]||'').get('tab');return tabs.some(x=>x[0]===t)?t:'profile'};
const switcher=()=>`<label class="account-mock">Mock 身份 <select data-account-identity aria-label="切换 Mock 用户身份"><option value="" disabled ${!getAuthUser()?'selected':''}>选择测试身份</option>${[['regular','普通用户 · 未申请'],['reviewing','普通用户 · 审核中'],['creator','认证主播 · 审核通过']].map(([id,label])=>`<option value="${id}" ${(getAuthUser()?.creatorApplicationStatus||'not_applied')===({regular:'not_applied',reviewing:'reviewing',creator:'approved'}[id])&&getAuthUser()?'selected':''}>${label}</option>`).join('')}</select></label>`;
const empty=(symbol,title,desc)=>`<div class="account-empty"><i>${symbol}</i><h3>${title}</h3><p>${desc}</p></div>`;
function tasks(){let data=ledger();return `<div class="account-subtabs" role="tablist" aria-label="任务中心"><button role="tab" aria-selected="${rewardTab==='list'}" data-reward-tab="list" class="${rewardTab==='list'?'selected':''}">任务列表</button><button role="tab" aria-selected="${rewardTab==='records'}" data-reward-tab="records" class="${rewardTab==='records'?'selected':''}">奖励记录</button></div>${rewardTab==='records'?`<div class="account-table"><div class="account-record header"><b>奖励来源</b><b>奖励内容</b><b>获得时间</b></div>${data.records.map(r=>`<div class="account-record"><span>${r.source}</span><strong>${esc(r.reward.replace(/EXP/g,'经验值'))}</strong><time>${r.time}</time></div>`).join('')}</div>`:`<div class="account-tasks">${data.tasks.map((t,i)=>`<article class="account-task"><i>${['☏','▶','♡'][i]}</i><div class="account-task-copy"><h3>${t.name}</h3><p>${t.desc}</p><div class="account-task-progress"><progress value="${t.current}" max="${t.total}" aria-label="${t.name}进度"></progress><small>${t.current} / ${t.total}</small></div></div><div class="account-task-reward">${reward(t)}</div>${t.status==='todo'?`<button class="account-secondary" data-task="${i}">去完成</button>`:'<span class="account-task-completed">✓ 已完成</span>'}</article>`).join('')}</div>`}`}
function recruitment(user){return applicationPage(user,()=>`<div class="account-recruit"><div><span class="page-eyebrow">SHENMA LIVE · CREATOR</span><h2>让热爱成为你的主场</h2><p>与球迷分享每一个精彩瞬间，开启你的直播旅程。</p></div><div class="account-recruit-art" aria-hidden="true"><span>▶</span><b>LIVE</b><i>✦</i></div></div><div class="account-creator-status"><span>✓ 已通过主播认证</span><h3>恭喜，你已经成为神马直播平台主播</h3><p>主播 ID：${esc(user.userId)}</p><a class="auth-primary account-cta" href="#/creator">进入主播工作台 →</a></div>`)}
function content(tab,user,hosts,streams,followedHosts){if(tab==='profile')return `<form data-account-profile class="account-profile-form"><div class="account-field"><label>用户头像</label><div class="account-avatar-edit"><img src="${esc(user.avatar)}" alt="当前头像"><button type="button" class="account-secondary" data-avatar-pick>修改头像</button><input type="file" accept="image/png,image/jpeg,image/webp" data-account-avatar hidden><small>支持 JPG、PNG、WebP，最大 5 MB</small></div></div><div class="account-field"><label for="accountNickname">用户昵称</label><div><input id="accountNickname" name="nickname" value="${esc(user.nickname)}" placeholder="请输入昵称" required><small>昵称长度为 2～8 位</small><p class="account-error" data-profile-error role="alert"></p></div></div><div class="account-field"><label>登录密码</label><div class="account-password"><span>••••••••</span><button type="button" class="account-text-button" data-account-dialog="password">修改密码</button></div></div><button class="auth-primary account-save" type="submit">保存修改</button></form>`;
if(tab==='checkin')return checkinPage();if(tab==='invite')return invitePage(user);if(tab==='tasks')return tasks();if(tab==='creator')return recruitment(user);
if(tab==='following'){let followed=hosts.filter(h=>followedHosts.has(h.id));return `<p class="account-intro">关注的声音，总能第一时间找到。<span>共 ${followed.length} 位主播</span></p>${!followed.length?empty('♡','暂无关注的主播','去直播页发现你喜欢的主播吧。'):''}<div class="account-host-grid">${followed.map((h,i)=>`<div class="account-host-shell"><a class="account-host" href="#/anchor/${h.id}"><div class="account-host-avatar"><img src="${h.avatar}" alt="${h.name}">${h.liveRoom?'<span class="account-live"><i></i>直播中</span>':''}</div><h3>${h.name}</h3><p>${(h.fans/10000).toFixed(1)}万 粉丝</p><small>上次直播：${['15分钟前','2小时前','35分钟前','1小时前','3小时前','3天前','2天前','5天前','6小时前'][i]}</small><span class="account-host-action">查看主播主页 →</span></a>${h.liveRoom?`<a class="account-host-live-entry" href="#/room/${h.liveRoom}">进入直播间 →</a>`:''}</div>`).join('')}</div>`}
if(tab==='history'){let categories=['足球','篮球','英雄联盟','美女','赛事解说'];let rows=Array.from({length:10},(_,i)=>{let category=categories[i%5],matches=streams.filter(r=>category==='赛事解说'?r.category==='足球':category==='美女'?r.presenterTag==='美女主播':r.category===category),room=matches[Math.floor(i/5)%matches.length]||streams[0];return {...room,live:[0,1,2,5].includes(i),category,time:['今天 10:25','今天 09:10','昨天 22:30','昨天 20:05','10月4日 19:30'][i%5],...(category==='美女'?{title:['米娜陪你聊球，分享观赛日常','晚间陪伴：丸子说球的球迷聊天室'][Math.floor(i/5)]}:{}),...(category==='赛事解说'?{title:['欧冠经典比赛战术复盘','英超争冠形势与球队分析'][Math.floor(i/5)]}:{})}});return `<p class="account-intro">你的精彩观赛足迹<span>最近 ${rows.length} 条记录</span></p><div class="account-history-grid">${rows.map((r,i)=>{let body=`${r.live?`<a href="#/room/${r.id}" aria-label="进入${esc(r.title)}直播间">`:""}<div class="cover"><img src="${r.cover}" alt="${esc(r.title)}" loading="lazy"><span class="account-history-status ${r.live?'live':''}">${r.live?'<i></i>直播中':'已结束'}</span><span class="account-category">${r.category}</span></div>${r.live?"</a>":""}<div class="card-copy">${r.live?`<a href="#/room/${r.id}">`:""}<h3>${esc(r.title)}</h3>${r.live?"</a>":""}<div class="host-row"><a href="#/anchor/${anchorIdOf(r)}"><img src="${r.avatar}" alt=""><span>${esc(r.host)}</span></a></div><small>直播时间：${r.time}</small></div>`;return `<article class="live-card ${r.live?'':'account-ended'}">${body}</article>`}).join('')}</div>`}
return empty({spending:'▤',checkin:'▦',gifts:'◇'}[tab],{spending:'暂无消费记录',checkin:'每日签到，敬请期待',gifts:'活动礼包即将上线'}[tab],{spending:'你的消费记录将在这里展示。',checkin:'签到规则与奖励正在准备中，记得常来看看。',gifts:'更多专属活动与惊喜礼包正在准备中。'}[tab])}
function modal(){if(!dialog)return '';return `<div class="account-backdrop"><section class="account-dialog" role="dialog" aria-modal="true" aria-label="修改密码"><button class="auth-modal-close" data-account-close aria-label="关闭">×</button><h2>修改登录密码</h2><form data-account-modal-form><label>绑定手机号<input value="${maskedPhone()}" readonly aria-readonly="true" autocomplete="off"></label><label>验证码<div class="account-code-field"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="one-time-code" placeholder="请输入验证码"><button class="account-text-button" type="button" data-account-code-send ${Date.now()<codeDeadline?'disabled':''}>${Date.now()<codeDeadline?`重新获取 ${Math.ceil((codeDeadline-Date.now())/1000)}s`:'获取验证码'}</button></div></label><label>新密码<input name="password" type="password" required minlength="6" maxlength="32" autocomplete="new-password"></label><label>确认新密码<input name="confirm" type="password" required minlength="6" maxlength="32" autocomplete="new-password"></label><p data-modal-error class="account-error" role="alert"></p><button class="auth-primary" type="submit">确认修改</button></form></section></div>`}
export function accountPage({header,footer,hosts,streams,followedHosts}){if(getAuthUser())settleTaskRewards();let user=getAuthUser(),tab=activeTab();if(!user)return `${header()}<main class="account-page"><div class="account-panel">${empty('♙','登录后查看个人中心','登录即可管理资料与查看你的账户信息。')}<button class="auth-primary account-guest-login" data-auth-open="login">立即登录</button>${switcher()}</div></main>${footer()}`;let count=hosts.filter(h=>followedHosts.has(h.id)).length;return `${header()}<main class="account-page"><div class="account-page-heading"><h1>个人中心</h1>${switcher()}</div><section class="account-summary"><div class="account-summary-user"><img src="${esc(user.avatar)}" alt="${esc(user.nickname)}"><div><h2>${esc(user.nickname)} <span class="account-vip-badge">VIP ${user.vip}</span></h2><p>用户 ID：${esc(user.userId)}</p><a href="#/profile/mock-user?tab=following">关注 <b>${count}</b> ›</a><div class="account-summary-vip"><div><b>VIP ${user.vip}</b><span>${user.exp.toLocaleString()} / ${user.nextExp.toLocaleString()} 经验值</span></div><progress value="${user.exp}" max="${user.nextExp}" aria-label="个人中心 VIP 升级进度"></progress><small>距离 VIP ${user.vip+1} 还需 ${Math.max(0,user.nextExp-user.exp).toLocaleString()} 经验值</small></div></div></div><div class="account-balance"><i>💎</i><div><small>我的钻石</small><b>${user.diamonds.toLocaleString()}</b></div></div><div class="account-balance"><i>🪙</i><div><small>我的金币</small><b>${user.coins.toLocaleString()}</b></div></div></section><div class="account-layout"><nav class="account-nav" aria-label="个人中心功能">${tabs.map(([id,label,symbol])=>`<a href="#/profile/mock-user?tab=${id}" ${id===tab?'aria-current="page"':''} class="${id===tab?'selected':''}"><i>${symbol}</i>${label}<span>›</span></a>`).join('')}</nav><section class="account-panel"><div class="account-content-heading"><h2>${tabs.find(t=>t[0]===tab)[1]}</h2></div>${content(tab,user,hosts,streams,followedHosts)}</section></div></main>${modal()}<div class="account-notice" role="status" aria-live="polite"></div>${footer()}`}

const notice=text=>{let node=document.querySelector('.account-notice');if(node){node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2800)}};
export function bindAccount(render){bindCheckin(render);bindInvite(render);bindApplication(render);document.querySelector('[data-avatar-pick]')?.addEventListener('click',()=>document.querySelector('[data-account-avatar]')?.click());document.querySelectorAll('[data-account-identity]').forEach(el=>el.onchange=()=>{resetApplication();switchMockUser(el.value);let key=el.value==='creator'?'creator':'regular';ledgers.delete(key);localStorage.removeItem('shenma-account-'+key);dialog=null;render()});document.querySelector('[data-account-profile]')?.addEventListener('submit',e=>{e.preventDefault();let name=new FormData(e.target).get('nickname').trim();if([...name].length<2||[...name].length>8){document.querySelector('[data-profile-error]').textContent='昵称长度需为 2～8 位';return}updateAuthUser({nickname:name});render();notice('个人资料已保存')});document.querySelector('[data-account-avatar]')?.addEventListener('change',e=>{let file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){notice('请选择 5 MB 以内的 JPG、PNG 或 WebP 图片');return}let reader=new FileReader();reader.onload=()=>{const save=avatar=>{try{updateAuthUser({avatar});render();notice('头像已更新')}catch{notice('头像保存失败，请重试')}};let image=new Image();image.onload=()=>{const scale=Math.min(1,512/Math.max(image.width,image.height));let canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);save(canvas.toDataURL('image/webp',.85))};image.onerror=()=>notice('图片无法读取，请选择有效的图片');image.src=reader.result};reader.readAsDataURL(file)});
document.querySelectorAll('[data-reward-tab]').forEach(b=>b.onclick=()=>{rewardTab=b.dataset.rewardTab;render()});document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{let t=ledger().tasks[+b.dataset.task];if(t.status==='todo')location.hash=t.name==='订阅主播'?'#/profile/mock-user?tab=following':'#/live'});
document.querySelectorAll('[data-account-dialog]').forEach(b=>b.onclick=()=>{previousFocus=b.dataset.accountDialog;dialog=b.dataset.accountDialog;codeSent=false;codeDeadline=0;clearInterval(codeTimer);render();document.querySelector('.account-dialog input')?.focus()});const close=()=>{clearInterval(codeTimer);dialog=null;render();document.querySelector(`[data-account-dialog="${previousFocus}"]`)?.focus()};document.querySelector('[data-account-close]')?.addEventListener('click',close);document.querySelector('.account-backdrop')?.addEventListener('click',e=>{if(e.target===e.currentTarget)close()});let popup=document.querySelector('.account-dialog');if(popup)popup.onkeydown=e=>{if(e.key==='Escape'){close();return}if(e.key==='Tab'){let fields=[...popup.querySelectorAll('button,input,select,textarea')].filter(n=>!n.disabled),first=fields[0],last=fields.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.querySelector('[data-account-code-send]')?.addEventListener('click',()=>{
  if(Date.now()<codeDeadline)return;
  if(maskedPhone()==='暂未绑定手机号'){document.querySelector('[data-modal-error]').textContent='请先绑定手机号';return}
  codeSent=true;codeDeadline=Date.now()+60000;
  document.querySelector('[data-modal-error]').textContent='验证码已发送（演示验证码：123456）';
  const refresh=()=>{const b=document.querySelector('[data-account-code-send]');if(!b){clearInterval(codeTimer);return}const seconds=Math.max(0,Math.ceil((codeDeadline-Date.now())/1000));b.disabled=seconds>0;b.textContent=seconds?`重新获取 ${seconds}s`:'获取验证码';if(!seconds)clearInterval(codeTimer)};
  refresh();clearInterval(codeTimer);codeTimer=setInterval(refresh,1000);
});document.querySelector('[data-account-modal-form]')?.addEventListener('submit',e=>{e.preventDefault();let data=new FormData(e.target);if(dialog==='password'&&(!codeSent||data.get('code')!=='123456')){document.querySelector('[data-modal-error]').textContent='请获取并输入正确的验证码';return}if(dialog==='password'&&data.get('password')!==data.get('confirm')){document.querySelector('[data-modal-error]').textContent='两次输入的密码不一致';return}close();notice('Mock 密码修改完成')});
}
window.addEventListener('hashchange',()=>{dialog=null;rewardTab='list';clearInterval(codeTimer)});
