import {getAuthUser} from './auth.js';
import './anchor.css';
import {getCreatorState,creatorAnchorId} from './creator-state.js';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let directory=[];
export function registerAnchors(hosts,streams){directory=hosts;streams.forEach(room=>{if(!hosts.some(h=>h.name===room.host))hosts.push({id:`host-${room.id}`,name:room.host,avatar:room.avatar,fans:18500+hosts.length*3700,liveRoom:room.id})});return hosts}
export function anchorIdOf(room){return directory.find(h=>h.name===(room.host||room.name))?.id||`host-${room.id}`}
export function ensureAnchor(room,isLive=true){let id=anchorIdOf(room);if(!directory.some(h=>h.id===id))directory.push({id,name:room.host,avatar:room.avatar,fans:28600,liveRoom:isLive?room.id:undefined});return id}
const dayKey=(offset=0)=>{let key=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Kuala_Lumpur'}),d=new Date(key+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};
function dateLabel(key){const date=new Date(key+'T12:00:00Z'),text=`${date.getUTCMonth()+1}月${date.getUTCDate()}日`;return `${key===dayKey()?'今天 · ':key===dayKey(1)?'明天 · ':key===dayKey(-1)?'昨天 · ':''}${text}`}
const fanCount=count=>count>=10000?`${(count/10000).toFixed(1)}万`:String(count);
export function anchorMock(host,events,streams){
 if(host.id==='qingning')return {plans:[],replays:[]};
 const index=Math.max(0,directory.findIndex(h=>h.id===host.id));
 const creator=host.id===creatorAnchorId?getCreatorState():null;
 const room=creator?.active?{matchId:creator.active.eventId}:streams.find(r=>r.id===host.liveRoom);
 const liveEvents=events.filter(e=>e.status==='live');
 const generatedMatch=/^match-host-(.+)-\d+$/.exec(host.liveRoom||'');
 const primary=liveEvents.find(e=>e.id===(room?.matchId||generatedMatch?.[1]))||liveEvents[index%liveEvents.length];
 const secondary=liveEvents.find(e=>e.sport!==(primary?.sport))||liveEvents.find(e=>e.id!==primary?.id);
 const upcoming=events.filter(e=>e.status==='upcoming'&&e.date>=dayKey()).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));
 const selected=upcoming.filter((e,i)=>i%Math.max(1,Math.floor(upcoming.length/8))===index%Math.max(1,Math.floor(upcoming.length/8))).slice(0,8);
 const fallback=upcoming.filter(e=>!selected.some(p=>p.id===e.id));
 while(selected.length<8&&fallback.length)selected.push(fallback.shift());
 const plans=[primary,secondary,...selected].filter(Boolean).map(e=>({...e,anchorRoom:e.id===(creator?creator.active?.eventId:primary?.id)?host.liveRoom:null})).sort((a,b)=>a.date.localeCompare(b.date)||((a.status==='live'?0:1)-(b.status==='live'?0:1))||a.time.localeCompare(b.time));
 const history=[['足球','英超焦点战｜阿森纳 VS 曼城','20:30','02:18:36'],['篮球','NBA 比赛复盘｜湖人 VS 勇士','09:00','01:52:18'],['英雄联盟','LPL 焦点对决｜BLG VS TES','18:00','03:06:42'],['足球','欧冠之夜｜皇马 VS 拜仁','03:00','02:35:20'],['篮球','CBA 主场之争｜广东 VS 辽宁','19:35','01:48:12'],['足球','西甲赛事解析｜巴萨 VS 马竞','22:00','02:10:45'],['英雄联盟','峡谷之巅｜赛前分析与实战教学','17:30','01:26:08'],['足球','意甲争冠战｜国米 VS 尤文','21:45','02:22:51'],['篮球','NBA 新赛季｜球队阵容观察','10:30','00:58:33'],['足球','五大联赛周末｜精彩进球盘点','20:00','01:15:06'],['篮球','CBA 焦点战｜北京 VS 上海','19:30','02:01:17'],['英雄联盟','世界赛复盘｜关键团战拆解','18:30','01:39:24']];
 const replays=history.map(([category,title,time,duration],i)=>{const candidates=streams.filter(s=>s.category===category||(category==='英雄联盟'&&s.league==='电竞'));const cover=(candidates[(index+i)%Math.max(1,candidates.length)]||streams[i%streams.length])?.cover;return {id:`${host.id}-replay-${i}`,category,title,time,duration,date:dayKey(-Math.floor(i/4)),cover,fallback:streams.find(s=>s.id===(category==='篮球'?'nba-lal':category==='英雄联盟'?'lpl':'premier-ars'))?.cover}});
 return {plans,replays};
}
function empty(title){return `<div class="anchor-empty"><i aria-hidden="true">${title.includes('预告')?'▦':'▷'}</i><p>${title}</p></div>`}
function groups(rows,render,kind){const keys=[...new Set(rows.map(r=>r.date))].sort((a,b)=>kind==='replay'?b.localeCompare(a):a.localeCompare(b));return keys.map(key=>`<section class="anchor-date-group"><h3>${dateLabel(key)}<small>${rows.filter(r=>r.date===key).length} ${kind==='replay'?'场回放':'场赛事'}</small></h3><div class="${kind==='replay'?'anchor-replay-grid':'anchor-plan-list'}">${rows.filter(r=>r.date===key).map(render).join('')}</div></section>`).join('')}
function planCard(event,matchLogo){const live=event.status==='live',href=live&&event.anchorRoom?`#/room/${event.anchorRoom}`:`#/match/${event.id}`;return `<a class="match-card anchor-plan" href="${href}" data-anchor-fixture="${event.id}" data-fixture-target="${live&&event.anchorRoom?'room':'match'}" aria-label="${esc(event.home)}对${esc(event.away)}，${live&&event.anchorRoom?'进入直播间':'查看赛事详情'}"><div class="anchor-plan-meta"><span class="match-sport ${event.sport}">${event.sport==='football'?'⚽ 足球':'🏀 篮球'}</span><b>${esc(event.league)}</b><time>${live?esc(event.stage):event.time}</time></div><div class="match-line-game"><div class="match-line-team home"><b>${esc(event.home)}</b>${matchLogo(event.home,event.color)}</div><strong class="match-line-score">${live?esc(event.score.replaceAll(':','-')):'VS'}</strong><div class="match-line-team away">${matchLogo(event.away,event.color)}<b>${esc(event.away)}</b></div></div><span class="anchor-plan-action ${live?'live':''}">${live?'<i></i>进行中':'未开赛'}<small>${live&&event.anchorRoom?'进入直播间':'赛事详情'} ›</small></span></a>`}
function replayCard(r){return `<button class="live-card anchor-replay" type="button" data-anchor-replay="${r.id}" aria-label="查看回放：${esc(r.title)}"><div class="cover"><img src="${r.cover}" alt="${esc(r.title)}" loading="lazy" onerror="this.onerror=null;this.src='${r.fallback}'"><span class="tag">${r.category}</span><span class="card-play">▶</span><span class="anchor-duration">${r.duration}</span></div><div class="card-copy"><h3>${esc(r.title)}</h3><p><time>${r.time}</time><span>时长 ${r.duration}</span></p></div></button>`}
function content(host,data,tab,matchLogo){const rows=tab==='schedule'?data.plans:data.replays;return rows.length?groups(rows,r=>tab==='schedule'?planCard(r,matchLogo):replayCard(r),tab==='schedule'?'plan':'replay'):empty(tab==='schedule'?'暂无直播预告':'暂无直播回放')}
export function anchorPage(id,{header,footer,hosts,events,streams,matchLogo,followedHosts}){const host=hosts.find(h=>h.id===id);if(!host)return `${header()}<main class="anchor-page">${empty('暂无该主播信息')}<a class="account-text-button" href="#/live">浏览直播 →</a></main>${footer()}`;const data=anchorMock(host,events,streams),intro=host.id==='qingning'?'分享赛场故事，新的直播内容正在准备中。':host.name.includes('篮球')||host.name==='小七'?'专注 NBA 与 CBA 赛事解说，一起聊战术、看精彩对决。':host.name.includes('电竞')?'分享电竞赛事分析与峡谷实战，每场精彩都不缺席。':'专注五大联赛赛事分析，每晚陪你看球，一起分享绿茵场上的热爱。';return `${header()}<main class="anchor-page"><section class="anchor-summary"><div class="anchor-profile-avatar ${host.liveRoom?'is-live':''}"><img src="${host.avatar}" alt="${esc(host.name)}">${host.liveRoom?'<span class="anchor-live-label"><i></i>LIVE</span>':''}</div><div class="anchor-summary-copy"><h1>${esc(host.name)}<span class="host-status ${host.liveRoom?'live':''}">${host.liveRoom?'直播中':'暂未开播'}</span></h1><p class="anchor-fans"><b>${fanCount(host.fans)}</b> 粉丝<span>ID：${esc(host.id)}</span></p><p class="anchor-description">${intro}</p></div><div class="anchor-summary-actions"><button type="button" class="follow-btn ${followedHosts.has(host.id)?'following':''}" ${getAuthUser()?`data-host-follow="${host.id}"`:'data-auth-open="login"'} aria-pressed="${followedHosts.has(host.id)}">${followedHosts.has(host.id)?'取消关注':'+ 关注'}</button>${host.liveRoom?`<a class="go-live anchor-enter" href="#/room/${host.liveRoom}">▶ 进入直播间</a>`:''}</div></section><section class="anchor-content"><nav class="anchor-tabs" role="tablist" aria-label="主播内容"><button type="button" role="tab" id="anchorScheduleTab" aria-controls="anchorContent" aria-selected="true" class="selected" data-anchor-tab="schedule">直播预告</button><button type="button" role="tab" id="anchorReplayTab" aria-controls="anchorContent" aria-selected="false" data-anchor-tab="replay">直播回放</button></nav><div id="anchorContent" role="tabpanel" aria-labelledby="anchorScheduleTab">${content(host,data,'schedule',matchLogo)}</div></section><div class="anchor-notice" role="status" aria-live="polite"></div></main>${footer()}`}
export function bindAnchor({hosts,events,streams,matchLogo}){let id=decodeURIComponent(location.hash.split('/').pop().split('?')[0]),host=hosts.find(h=>h.id===id);if(!document.querySelector('.anchor-page')||!host)return;const data=anchorMock(host,events,streams);const bindReplays=()=>document.querySelectorAll('[data-anchor-replay]').forEach(b=>b.onclick=()=>{const notice=document.querySelector('.anchor-notice');notice.textContent='回放播放功能即将开放';notice.classList.add('show');setTimeout(()=>notice.classList.remove('show'),2600)});const select=tab=>{document.querySelectorAll('[data-anchor-tab]').forEach(b=>{let active=b.dataset.anchorTab===tab;b.classList.toggle('selected',active);b.setAttribute('aria-selected',String(active))});const panel=document.querySelector('#anchorContent');panel.setAttribute('aria-labelledby',tab==='schedule'?'anchorScheduleTab':'anchorReplayTab');panel.innerHTML=content(host,data,tab,matchLogo);bindReplays()};document.querySelectorAll('[data-anchor-tab]').forEach(b=>{b.onclick=()=>select(b.dataset.anchorTab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let tab=e.key==='Home'?'schedule':e.key==='End'?'replay':b.dataset.anchorTab==='schedule'?'replay':'schedule';select(tab);document.querySelector(`[data-anchor-tab="${tab}"]`).focus()}}});bindReplays()}
