import { liveRooms, hotRooms, standings, initials } from './data.js';

const app = document.querySelector('#app');
const navs = [['首页','#/'],['直播','#/live'],['预告','#/schedule'],['赛事','#/matches'],['聊天','#/chat']];
let activeLive = 0, footballLeague = '英超', basketballLeague = 'NBA', nbaConference = 'east';

const icon = (name) => ({search:'⌕', game:'◈', download:'⇩', cast:'◉', fire:'🔥', play:'▶', more:'›', arrow:'↗', bell:'●'}[name] || '');
const teamMark = (name, code) => `<span class="team-mark ${code.toLowerCase()}">${initials(name)}</span>`;

function header(){ const route=location.hash||'#/'; return `<header class="site-header"><div class="header-inner"><a class="brand" href="#/" aria-label="神马直播 首页"><span class="brand-mark">S</span><span>神马直播</span></a><nav class="main-nav">${navs.map(([n,h])=>`<a href="${h}" class="${route===h?'active':''}">${n}</a>`).join('')}</nav><form class="search" id="searchForm"><span>${icon('search')}</span><input id="searchInput" placeholder="搜索赛事、主播、球队" autocomplete="off"><button aria-label="搜索">搜索</button></form><div class="header-actions"><button class="utility" data-action="game"><i>${icon('game')}</i>游戏</button><button class="utility" data-action="download"><i>${icon('download')}</i>下载 App</button><button class="go-live" data-action="cast">${icon('cast')} 开播</button><button class="avatar-btn" id="avatarBtn"><img src="https://i.pravatar.cc/100?img=49" alt="当前用户头像"><span class="online-dot"></span></button><div class="user-menu" id="userMenu"><b>晚上好，神马直播用户</b><a href="#/profile">个人中心</a><a href="#/creator">创作中心</a><button data-action="logout">退出登录</button></div></div></div></header>`; }
function sectionHead(title, href='#/live'){return `<div class="section-head"><h2>${title}</h2><a href="${href}">更多 <b>${icon('more')}</b></a></div>`}
function liveCard(r){return `<a class="live-card" href="#/room/${r.id}" aria-label="进入直播间：${r.title}"><div class="cover"><img src="${r.cover}" alt="" aria-hidden="true" loading="lazy" onerror="this.style.visibility='hidden'"><span class="tag" style="--tag:${r.color}">${r.presenterTag}</span><span class="card-play">${icon('play')}</span></div><div class="card-copy"><h3>${r.title}</h3><div class="host-row"><img src="${r.avatar}" alt="${r.host}"><span>${r.host}</span><em>${icon('fire')} ${r.heat}</em></div></div></a>`}
function featured(){ let r=liveRooms[activeLive]; return `<section class="featured"><div class="stage"><img src="${r.cover}" alt="${r.title}"><div class="stage-shade"></div><div class="live-pill"><i></i> 正在直播</div><button class="stage-play" aria-label="播放直播">${icon('play')}</button><div class="stage-meta"><img src="${r.avatar}" alt="${r.host}"><span><b>${r.host}</b><small>${icon('fire')} ${r.heat} 人正在观看</small></span><button>进入直播间 ${icon('arrow')}</button></div></div><div class="channel-list" aria-label="直播间切换">${liveRooms.map((x,i)=>`<button class="channel ${i===activeLive?'selected':''}" data-channel="${i}" aria-label="切换至${x.title}"><img src="${x.cover}" alt="${x.title}"></button>`).join('')}</div></section>`}
function footballTable(){let data=standings.football[footballLeague]; return `<div class="rank-card football-rank"><div class="rank-tabs">${Object.keys(standings.football).map(x=>`<button class="${x===footballLeague?'selected':''}" data-football="${x}">${x}</button>`).join('')}</div><div class="rank-title"><span>足球球队排行</span><small>${footballLeague} · 2023/24</small></div><div class="rank-table football-table"><div class="rank-row table-head"><span>排名</span><span>球队</span><span>赛</span><span>胜</span><span>平</span><span>负</span><span>进/失</span><span>积分</span></div>${data.map((t,i)=>`<a href="#/team/${encodeURIComponent(t[1])}" class="rank-row"><span class="rank-num n${i+1}">${i+1}</span><span class="team">${teamMark(t[0],t[1])}<b>${t[0]}</b></span><span>${t[2]}</span><span>${t[3]}</span><span>${t[4]}</span><span>${t[5]}</span><span>${t[6]}</span><strong>${t[7]}</strong></a>`).join('')}</div></div>`}
function basketballTable(){ let list=basketballLeague==='NBA'?standings.basketball.NBA[nbaConference]:standings.basketball.CBA.all; return `<div class="rank-card basketball-rank"><div class="rank-tabs"><button class="${basketballLeague==='NBA'?'selected':''}" data-basketball="NBA">NBA</button><button class="${basketballLeague==='CBA'?'selected':''}" data-basketball="CBA">CBA</button></div><div class="rank-title"><span>篮球球队排行</span>${basketballLeague==='NBA'?`<div class="conference"><button class="${nbaConference==='east'?'on':''}" data-conf="east">东部</button><button class="${nbaConference==='west'?'on':''}" data-conf="west">西部</button></div>`:'<small>常规赛</small>'}</div><div class="rank-table basketball-table"><div class="rank-row table-head"><span>排名</span><span>球队</span><span>胜</span><span>负</span><span>胜率</span><span>胜差</span><span>近况</span></div>${list.map((t,i)=>`<a href="#/team/${encodeURIComponent(t[1])}" class="rank-row"><span class="rank-num n${i+1}">${i+1}</span><span class="team">${teamMark(t[0],t[1])}<b>${t[0]}</b></span><span>${t[2]}</span><span>${t[3]}</span><span>${t[4]}</span><span>${t[5]}</span><span class="form">${t[6]}</span></a>`).join('')}</div></div>`}
function footer(){return `<footer><div class="footer-inner"><div class="footer-brand"><span class="brand-mark">S</span><b>神马直播</b><p>与你一起，见证每一场热爱。</p></div><div class="footer-links"><span>平台服务</span><span>帮助中心</span><span>商务合作</span><span>用户协议</span><span>隐私政策</span></div><div class="copyright">© 2026 神马直播. All rights reserved.</div></div></footer>`}
function home(){return `${header()}<main><div class="featured-wrap">${featured()}</div><section class="content-section hot">${sectionHead('热门直播')}${`<div class="live-grid">${hotRooms.map(liveCard).join('')}</div>`}</section><section class="content-section standings">${sectionHead('球队排行','#/matches')}<div class="ranking-grid">${footballTable()}${basketballTable()}</div></section></main>${footer()}`}
function simplePage(kind, text){return `${header()}<main class="subpage"><div class="subpage-card"><span class="page-eyebrow">SMLIVE WEB</span><h1>${kind}</h1><p>${text}</p><a class="go-live" href="#/">返回首页</a></div></main>${footer()}`}
function detailPage(type, id){ let room=[...liveRooms,...hotRooms].find(x=>x.id===id); return `${header()}<main class="subpage"><div class="detail-card">${room?`<img src="${room.cover}" alt="${room.title}"><div><span class="tag" style="--tag:${room.color}">${room.league}</span><h1>${room.title}</h1><p>${room.host} · ${room.heat} 人气 · 直播间详情页已建立</p><button class="go-live" data-action="watch">进入观看</button></div>`:`<div><span class="tag">球队</span><h1>${decodeURIComponent(id)} 球队详情</h1><p>球队 ID：${decodeURIComponent(id)}。后续将在此接入赛程、阵容、新闻与数据。</p><a class="go-live" href="#/matches">查看赛事排行</a></div>`}</div></main>${footer()}`}
function render(){let h=location.hash||'#/'; if(h==='#/'||h==='') app.innerHTML=home(); else if(h.startsWith('#/room/'))app.innerHTML=detailPage('room',h.split('/').pop()); else if(h.startsWith('#/team/'))app.innerHTML=detailPage('team',h.split('/').pop()); else {let map={'#/live':['直播','正在筹备所有直播内容，这里将成为完整的赛事直播频道。'],'#/schedule':['预告','精彩赛事预告会在这里按时间为你呈现。'],'#/matches':['赛事','赛事中心与完整球队排行已为后续开发预留。'],'#/chat':['聊天','与球迷一起，聊你所热爱的比赛。']}; app.innerHTML=simplePage(...(map[h]||['页面不存在','请返回首页继续浏览。']));} bind(); }
function bind(){document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>{activeLive=+b.dataset.channel;render(); window.scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-football]').forEach(b=>b.onclick=()=>{footballLeague=b.dataset.football;render()});document.querySelectorAll('[data-basketball]').forEach(b=>b.onclick=()=>{basketballLeague=b.dataset.basketball;render()});document.querySelectorAll('[data-conf]').forEach(b=>b.onclick=()=>{nbaConference=b.dataset.conf;render()});let avatar=document.querySelector('#avatarBtn'), menu=document.querySelector('#userMenu'); if(avatar) avatar.onclick=e=>{e.stopPropagation();menu.classList.toggle('open')};document.onclick=e=>{if(menu&&!menu.contains(e.target))menu.classList.remove('open')};document.querySelector('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();let q=document.querySelector('#searchInput').value.trim();if(q) alert(`正在搜索「${q}」\n搜索结果页将为你展示相关赛事、主播和球队。`)});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='game')location.hash='#/game'; else if(a==='download')location.hash='#/download'; else if(a==='cast')location.hash='#/creator'; else if(a==='watch')alert('直播播放功能已就绪（原型演示）'); else if(a==='logout')alert('已退出登录（原型演示）')});}
window.addEventListener('hashchange',()=>{activeLive=0;render();window.scrollTo({top:0,behavior:'smooth'})});render();
