import { getAuthUser } from './auth.js';
const KEY='shenma-creator-workspace-v1';
export const creatorRoomId='creator-sm884208';
export const creatorAnchorId='achen';
export const creatorDate=(offset=0)=>{const key=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Kuala_Lumpur'});const d=new Date(key+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};
export const creatorTimestamp=(date=new Date())=>date.toLocaleString('sv-SE',{timeZone:'Asia/Kuala_Lumpur'}).slice(0,16);
let cached;
const clone=value=>JSON.parse(JSON.stringify(value));
function initial(events,streams){const upcoming=events.filter(e=>e.status==='upcoming').slice(0,4);const covers=['premier-ars','nba-lal','lpl'].map(id=>streams.find(r=>r.id===id)?.cover||streams[0]?.cover);const plans=Array.from({length:8},(_,i)=>{const event=i<4?upcoming[i]:null;return {id:'creator-plan-'+i,category:event?(event.sport==='football'?'足球':'篮球'):['英雄联盟','娱乐','足球','篮球'][i-4],league:event?.league||'',eventId:event?.id||'',title:event?`${event.league}焦点战｜${event.home} VS ${event.away}`:['峡谷实战教学与赛事讨论','晚间陪你聊球','五大联赛周末复盘','NBA 赛后战术解析'][i-4],cover:covers[i%3],scheduledAt:`${creatorDate(i<5?i%4:-(i-4))} ${event?.time||['18:30','20:00','21:30'][i%3]}`,status:i<5?'pending':i<7?'completed':'cancelled'}});return {profile:{nickname:getAuthUser().nickname,avatar:getAuthUser().avatar,userId:getAuthUser().userId},active:null,draft:{category:'',league:'',eventId:'',title:'',cover:''},plans}}
export function getCreatorState(events=[],streams=[]){if(cached)return cached;try{const stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored?.plans?.length===8&&stored.profile){cached=stored;return cached}}catch{}if(!getAuthUser()?.isCreator)return null;cached=initial(events,streams);persistCreator();return cached}
export function persistCreator(){localStorage.setItem(KEY,JSON.stringify(cached))}
function authorized(){if(!getAuthUser()?.isCreator)throw new Error('仅认证主播可以操作工作台');return cached}
export function updateCreatorDraft(patch){const s=authorized();if(s.active){s.draft={...s.draft,title:patch.title??s.draft.title,cover:patch.cover??s.draft.cover}}else s.draft={...s.draft,...patch};persistCreator()}
export function validateCreatorSetup(draft){if(!draft.category)return '请选择直播分类';if(!draft.title.trim())return '请输入直播标题';if([...draft.title.trim()].length>50)return '直播标题最多 50 个字';if(!draft.cover)return '请上传或选择直播封面';return ''}
export function beginCreatorLive(setup,planId=null){const s=authorized();if(s.active)throw new Error('当前已有直播，请前往开播工作台管理');const error=validateCreatorSetup(setup);if(error)throw new Error(error);if(planId&&!s.plans.some(p=>p.id===planId&&p.status==='pending'))throw new Error('该计划当前不可开播');s.draft={category:setup.category,league:setup.league||'',eventId:setup.eventId||'',title:setup.title.trim(),cover:setup.cover};s.active={...s.draft,roomId:creatorRoomId,startedAt:Date.now(),viewers:1286,planId};if(planId)s.plans.find(p=>p.id===planId).status='live';persistCreator()}
export function saveCreatorLive(patch){const s=authorized();if(!s.active)throw new Error('当前没有正在进行的直播');const error=validateCreatorSetup({...s.active,...patch});if(error)throw new Error(error);s.active.title=patch.title.trim();s.active.cover=patch.cover;s.draft={...s.draft,title:s.active.title,cover:s.active.cover};if(s.active.planId){const p=s.plans.find(p=>p.id===s.active.planId);p.title=s.active.title;p.cover=s.active.cover}persistCreator()}
export function cancelCreatorPlan(id){const s=authorized();const plan=s.plans.find(p=>p.id===id);if(!plan||plan.status!=='pending')throw new Error('该计划当前不可取消');plan.status='cancelled';persistCreator()}
export function setCreatorMockMode(mode,events,streams){authorized();cached=initial(events,streams);if(mode==='live'){const p=cached.plans[0];cached.draft={category:p.category,league:p.league,eventId:p.eventId,title:p.title,cover:p.cover};cached.active={...cached.draft,roomId:creatorRoomId,startedAt:Date.now()-5198000,viewers:1286,planId:p.id};p.status='live'}persistCreator()}
export function syncCreatorPublic(hosts,rooms,events,streams){const s=getCreatorState(events,streams);if(!s)return;const u=getAuthUser();if(u?.isCreator){s.profile={nickname:u.nickname,avatar:u.avatar,userId:u.userId};persistCreator()}const host=hosts.find(h=>h.id===creatorAnchorId);if(host){host.name=s.profile.nickname;host.avatar=s.profile.avatar;host.liveRoom=s.active?creatorRoomId:undefined}if(s.active){const template=streams.find(r=>r.category===s.active.category)||streams[0];rooms.set(creatorRoomId,{...template,id:creatorRoomId,host:s.profile.nickname,avatar:s.profile.avatar,title:s.active.title,cover:s.active.cover,category:s.active.category,league:s.active.league,matchId:s.active.eventId||undefined,heat:s.active.viewers.toLocaleString(),presenterTag:'认证主播'})}else rooms.delete(creatorRoomId)}
export function creatorDuration(seconds){const value=Math.max(0,Math.floor(seconds));return [Math.floor(value/3600),Math.floor(value/60)%60,value%60].map(v=>String(v).padStart(2,'0')).join(':')}
export function creatorHistory(streams){return Array.from({length:60},(_,i)=>{const day=Math.floor(i/2),n=i%2,category=['足球','篮球','英雄联盟'][i%3],cover=streams.find(r=>r.category===category)?.cover||streams[i%streams.length]?.cover;return {id:'record-'+i,date:creatorDate(-day),start:`${creatorDate(-day)} ${n?'20:30':'10:00'}`,title:['英超焦点战｜阿森纳 VS 曼城','NBA 赛后解析｜湖人 VS 勇士','LPL 对决｜BLG VS TES'][i%3],cover,seconds:5400+(i*917)%4800,views:2860+(i*683)%8400,givers:60+(i*29)%320,fans:28+(i*17)%170,diamonds:1350+(i*271)%5300,coins:8650+(i*1637)%26800}})}
export function creatorPeriodRows(rows,period){const today=creatorDate(),start=creatorDate(period==='week'?-6:period==='month'?-29:period==='yesterday'?-1:0),end=period==='yesterday'?creatorDate(-1):today;return rows.filter(r=>r.date>=start&&r.date<=end)}
export function creatorTotals(rows){return rows.reduce((total,r)=>{for(const key of ['diamonds','coins','views','fans','seconds'])total[key]+=r[key];total.sessions++;return total},{diamonds:0,coins:0,views:0,fans:0,seconds:0,sessions:0})}
export function creatorDailyRows(rows){return [...new Set(rows.map(r=>r.date))].sort((a,b)=>b.localeCompare(a)).map(date=>({date,...creatorTotals(rows.filter(r=>r.date===date))}))}
export function creatorAudience(rows){const total=creatorTotals(rows),names=['南看台小周','晴天有球','小熊看球','橙子汽水','林间晚风','绿茵漫步','阿明聊球','北岸球迷','星河','夏日看台','蓝白故事','一颗篮球','小宇同学','秋日晴空','晚安球场'],weights=[24,18,15,12,10,8,5,4,3,1,0,0,0,0,0];return names.map((name,i)=>({name,avatar:`https://i.pravatar.cc/80?img=${[12,25,32,41,14,49,7,20,44,56,36,45,51,47,13][i]}`,following:i%4!==1,diamonds:Math.floor(total.diamonds*weights[i]/100),coins:Math.floor(total.coins*weights[i]/100)}))}
