import {prizes,gameTypes,loadGame,drawGame,settleGame,saveGame,siteRecords,createSiteRecord} from './game-state.js';
import './game.css';
let state=loadGame(),spinning=false,rotation=0,tab='site',result=null,timer=null,feedTimer=null,latestSiteRecord=siteRecords[0];
if(state.pending){result=settleGame(state);saveGame(state);}
const prizeOf=r=>prizes.find(p=>p.id===r.prizeId);
const amount=p=>p.id==='none'?'未中奖':p.id==='free'?`+${p.quantity} 次`:`×${p.quantity}`;
const time=t=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false});
function siteAnnouncement(){const r=latestSiteRecord,p=prizeOf(r);return `<div class="game-announcement" data-game-announcement role="status"><span class="game-announcement-label">🎉 最新喜报</span><span class="game-announcement-copy"><b>${r.nickname}</b> 刚刚获得 <i>${p.icon}</i> <strong>${p.name} ${amount(p)}</strong></span></div>`;}
function records(){const list=tab==='mine'?state.records.filter(r=>r.id!==state.pending):siteRecords;return `<div class="game-record-head"><span>${tab==='mine'?'中奖时间':'用户'}</span><span>奖品 / 数量</span></div><div class="game-record-list ${tab==='site'?'game-site-list':''}"><div class="game-record-track">${list.length?list.map(r=>{const p=prizeOf(r);return `<div class="game-record">${tab==='mine'?`<time>${time(r.time)}</time>`:`<div class="game-record-user"><i>${r.avatar}</i><div><b>${r.nickname}</b><time>${time(r.time)}</time></div></div>`}<span><i>${p.icon}</i><b>${p.name}</b><small>${amount(p)}</small></span></div>`}).join(''):'<div class="game-empty">🎟️<b>幸运故事，从这里开始</b><p>点击立即夺宝，收获你的第一条记录</p></div>'}</div></div>`;}
function modal(){if(!result)return '';const p=prizeOf(result);return `<div class="game-modal-backdrop"><section class="game-result" role="dialog" aria-modal="true" aria-labelledby="game-result-title" tabindex="-1"><button class="game-modal-close" aria-label="关闭中奖结果" data-result-close>×</button><div class="game-result-sparkles">✦ · ✧ · ✦</div><div class="game-result-icon">${p.icon}</div><h2 id="game-result-title">${p.id==='none'?'这次幸运擦肩而过':'恭喜你，夺宝成功！'}</h2><strong>${p.name} ${p.id==='none'?'':amount(p)}</strong><p>${p.id==='free'?'奖励次数已自动加入，可继续夺宝。':p.id==='none'?'别灰心，下一次幸运也许就属于你。':'奖品已记入你的夺宝记录。'}</p><button class="game-primary" data-result-close>知道了</button></section></div>`;}
export function gamePage({header,footer}){return `${header()}<main class="game-page"><div class="game-heading"><div><span class="game-eyebrow">神马游戏 · 娱乐时刻</span><h1>游戏中心 <span>把幸运，转出来</span></h1></div></div><nav class="game-types" aria-label="游戏类型">${gameTypes.map(g=>`<button ${g.available?'aria-current="page"':'disabled'} class="${g.available?'selected':''}"><i>${g.icon}</i>${g.name}${g.available?'<small>正在游玩</small>':'<small>敬请期待</small>'}</button>`).join('')}</nav><div class="game-layout"><section class="game-arena"><div class="game-arena-heading"><div><span>好运即将开启</span><h2>幸运夺宝</h2></div><span class="game-tag">8 重惊喜等你开启</span></div><p class="game-arena-copy">每一次转动，都有新的期待</p>${siteAnnouncement()}<div class="game-wheel-wrap"><div class="game-pointer" aria-label="中奖指针">▼</div><div class="game-wheel" style="transform:rotate(${rotation}deg)">${prizes.map((p,i)=>`<div class="game-prize" style="--angle:${i*45}deg"><i>${p.icon}</i><b>${p.name}</b><small>${amount(p)}</small></div>`).join('')}</div><div class="game-wheel-center">神马<span>幸运夺宝</span></div></div><button class="game-primary game-spin" data-game-spin ${spinning||!state.chances?'disabled':''}>${spinning?'幸运转动中…':!state.chances?'夺宝次数不足':'立即夺宝'} <span>↗</span></button><p class="game-spin-note" role="status">${spinning?'转盘正在揭晓你的幸运奖品':!state.chances?'<a href="#/profile/mock-user?tab=tasks">前往任务中心，获取更多夺宝次数 ›</a>':'每次消耗 1 次夺宝机会 · 免费次数奖励自动累加'}</p><details class="game-rules"><summary>玩法与概率说明 <span>＋</span></summary><p>每次夺宝消耗 1 次机会，获得免费抽奖奖励时自动增加 3 次。首次赠送 10 次机会，夺宝次数与历史记录自动保存。</p><div>${prizes.map(p=>`<span>${p.icon} ${p.name} ${p.weight}%</span>`).join('')}</div></details><p class="game-storage-note" role="status"></p></section><aside class="game-sidebar"><section class="game-my"><div><h2>我的夺宝</h2><span>好运由你开启</span></div><div class="game-chances"><strong>${state.chances}</strong><span>剩余夺宝次数</span><i>🎟️</i></div><a class="game-get" href="#/profile/mock-user?tab=tasks">获取夺宝次数 <span>›</span></a><p>完成任务，解锁更多幸运机会</p></section><section class="game-history"><div class="game-history-heading"><h2>夺宝记录</h2><span>✦ 幸运时刻</span></div><div class="game-tabs" role="tablist" aria-label="夺宝记录"><button role="tab" aria-selected="${tab==='site'}" data-game-tab="site" class="${tab==='site'?'selected':''}">全站记录 <i></i></button><button role="tab" aria-selected="${tab==='mine'}" data-game-tab="mine" class="${tab==='mine'?'selected':''}">我的记录</button></div><div data-game-records>${records()}</div></section></aside></div></main>${modal()}${footer()}`;}
function persist(){const ok=saveGame(state);if(!ok){const el=document.querySelector('.game-storage-note');if(el)el.textContent='浏览器存储不可用，本次记录仅在当前页面保留。';}}
function refreshSiteFeed(){
  if(!document.querySelector('.game-page')||document.hidden)return;
  latestSiteRecord=createSiteRecord();
  siteRecords.unshift(latestSiteRecord);
  siteRecords.length=Math.min(siteRecords.length,18);
  document.querySelector('[data-game-announcement]')?.replaceWith(document.createRange().createContextualFragment(siteAnnouncement()));
  if(tab==='site'){
    const panel=document.querySelector('[data-game-records]');
    if(panel){panel.innerHTML=records();panel.querySelector('.game-record-track')?.classList.add('game-feed-enter');}
  }
}
export function bindGame(render){
clearInterval(feedTimer);feedTimer=null;
if(!document.querySelector('.game-page')){tab='site';return;}
feedTimer=setInterval(refreshSiteFeed,3600);
document.querySelectorAll('[data-game-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.gameTab;document.querySelectorAll('[data-game-tab]').forEach(el=>{el.classList.toggle('selected',el.dataset.gameTab===tab);el.setAttribute('aria-selected',String(el.dataset.gameTab===tab));});document.querySelector('[data-game-records]').innerHTML=records();});document.querySelector('[data-game-spin]')?.addEventListener('click',()=>{if(spinning||state.chances<=0)return;const draw=drawGame(state);if(!draw)return;spinning=true;result=null;persist();render();const index=prizes.findIndex(p=>p.id===draw.prize.id),target=(360-index*45)%360;rotation+=1800+(target-rotation%360+360)%360;requestAnimationFrame(()=>requestAnimationFrame(()=>{const wheel=document.querySelector('.game-wheel');if(wheel)wheel.style.transform=`rotate(${rotation}deg)`;}));clearTimeout(timer);timer=setTimeout(()=>{result=settleGame(state);spinning=false;persist();if(document.querySelector('.game-page'))render();},4800);});document.querySelectorAll('[data-result-close]').forEach(b=>b.onclick=()=>{result=null;render();document.querySelector('[data-game-spin]')?.focus();});const dialog=document.querySelector('.game-result');if(dialog){dialog.focus();dialog.onkeydown=e=>{if(e.key==='Escape'){result=null;render();document.querySelector('[data-game-spin]')?.focus();}if(e.key==='Tab'){const buttons=[...dialog.querySelectorAll('button')];if(e.shiftKey&&document.activeElement===buttons[0]||!e.shiftKey&&document.activeElement===buttons.at(-1)||document.activeElement===dialog){e.preventDefault();(e.shiftKey?buttons.at(-1):buttons[0]).focus();}}};}}
