import {getAuthUser} from './auth.js';
import './invite.css';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let limit=8;
export const inviteReward=88;
export function invitationRows(empty=false){if(empty)return [];const names=['足球小王','南看台阿林','篮球小七','绿茵漫步','橙子看球','北岸球迷','晴天有球','林间晚风','热刺小周','阿明聊球','夏日球场','星河看台'];return names.map((name,i)=>{const date=new Date();date.setDate(date.getDate()-Math.floor(i/3));return {id:i,name,avatar:`https://i.pravatar.cc/80?img=${[12,14,25,32,41,7,49,20,44,56,36,45][i]}`,time:date.toLocaleDateString('sv-SE',{timeZone:'Asia/Kuala_Lumpur'})+' '+['09:20','08:45','08:10'][i%3],success:i!==3&&i!==9}})}
export function invitationTotals(rows){const count=rows.filter(row=>row.success).length;return {count,diamonds:count*inviteReward}}
function qrImage(code){let seed=[...code].reduce((n,c)=>n*31+c.charCodeAt(0),7)>>>0;let rects='';const finder=(x,y)=>{rects+=`<rect x="${x}" y="${y}" width="7" height="7"/><rect x="${x+1}" y="${y+1}" width="5" height="5" fill="white"/><rect x="${x+2}" y="${y+2}" width="3" height="3"/>`};for(let y=0;y<29;y++)for(let x=0;x<29;x++){if((x<8&&y<8)||(x>20&&y<8)||(x<8&&y>20))continue;seed=(seed*1664525+1013904223)>>>0;if(seed>>>30&1)rects+=`<rect x="${x}" y="${y}" width="1" height="1"/>`}finder(0,0);finder(22,0);finder(0,22);return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -3 35 35" shape-rendering="crispEdges"><rect x="-3" y="-3" width="35" height="35" fill="white"/><g fill="#29313d">${rects}</g></svg>`)}
export function invitationLink(user){return `${location.origin}${import.meta.env.BASE_URL}?invite=${encodeURIComponent(user.userId)}`}
export function invitePage(user){const rows=invitationRows(),totals=invitationTotals(rows),link=invitationLink(user);return `<div class="invite-page"><section class="invite-poster"><img src="https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=85" alt="足球运动员在绿茵赛场上拼搏"><div><span>与好友共享每场精彩</span><h3>邀请好友一起看球</h3><p>好友注册成功，你得 <b>88</b> 钻石</p><small>邀请越多，奖励越多</small><div class="invite-steps">邀请好友 <i>→</i> 好友注册 <i>→</i> 获得钻石</div></div></section><section class="invite-summary" aria-label="邀请奖励与统计"><article class="invite-reward"><small>每邀请1位好友</small><b>+88 <span>钻石</span></b><p>每成功邀请1位新用户，可获得88钻石</p></article><article><small>成功邀请人数</small><div class="invite-count-row"><b>${totals.count}<span> 人</span></b><button type="button" class="invite-record-jump" data-invite-record-jump aria-label="查看我的邀请记录">→</button></div></article><article><small>累计获得钻石</small><b>${totals.diamonds.toLocaleString('zh-CN')}<span> 钻石</span></b></article></section><p class="invite-reward-note">邀请1人得88钻石 · 邀请5人得440钻石 · 邀请10人得880钻石<br>邀请越多，累计获得的钻石越多</p><section class="invite-section"><h3>邀请方式</h3><div class="invite-share"><div class="invite-qr"><img src="${qrImage(user.userId)}" alt="${esc(user.nickname)}的专属邀请二维码"><b>好友扫码注册神马直播</b></div><div class="invite-link"><label for="inviteLink">你的专属邀请链接</label><div><input id="inviteLink" readonly value="${esc(link)}"><button class="account-secondary" type="button" data-invite-copy="link">复制</button></div><p>好友通过你的链接注册，即可计入有效邀请。</p></div></div></section><section class="invite-section"><h3>邀请规则</h3><ol>${['每成功邀请1位新用户注册，可获得88钻石。','被邀请用户需通过邀请人的专属链接或二维码完成注册。','同一用户只能被计入一次有效邀请。','邀请奖励在好友满足有效邀请条件后发放。','如存在作弊、批量注册或异常账号行为，平台有权取消对应奖励。','活动最终解释权归神马直播平台所有。'].map(text=>`<li>${text}</li>`).join('')}</ol></section><section class="invite-section invite-record-section" id="inviteRecords"><div class="invite-record-heading"><h3>我的邀请记录（${rows.length}）</h3></div>${rows.length?`<div class="invite-table-wrap"><table class="invite-table"><thead><tr><th>用户</th><th>注册时间</th><th>邀请状态</th><th>获得奖励</th></tr></thead><tbody>${rows.slice(0,limit).map(row=>`<tr><td><span><img src="${row.avatar}" alt="">${row.name}</span></td><td><time>${row.time}</time></td><td><span class="invite-status ${row.success?'success':''}">${row.success?'已成功':'待完成'}</span></td><td class="${row.success?'invite-earned':''}">${row.success?'+88 钻石':'待发放'}</td></tr>`).join('')}</tbody></table></div>${limit<rows.length?'<button type="button" class="account-secondary invite-more" data-invite-more>查看更多</button>':''}`:'<div class="account-empty invite-empty"><i>♡</i><h3>暂无邀请记录</h3><p>分享邀请链接，邀请好友加入神马直播吧</p></div>'}</section></div>`}
export function bindInvite(render){document.querySelector('[data-invite-record-jump]')?.addEventListener('click',()=>document.querySelector('#inviteRecords')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}));document.querySelector('[data-invite-more]')?.addEventListener('click',()=>{limit+=8;render()});document.querySelectorAll('[data-invite-copy]').forEach(button=>button.onclick=async()=>{const link=invitationLink(getAuthUser());try{await navigator.clipboard.writeText(link);const toast=document.querySelector('.account-notice');toast.textContent='邀请链接已复制';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}catch{const toast=document.querySelector('.account-notice');toast.textContent='复制失败，请选中邀请链接手动复制';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}})}
window.addEventListener('hashchange',()=>{limit=8});
