import { newsItems } from './news-data.js';
import './news.css';
const escape=text=>String(text).replace(/[&<>"']/g,value=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[value]));
const imageFallback=sport=>sport==='basketball'?'https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=1100&q=85':'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1100&q=85';
export const newsUrl=id=>import.meta.env.BASE_URL==='/'?`/news/${encodeURIComponent(id)}`:`${import.meta.env.BASE_URL}#/news/${encodeURIComponent(id)}`;
export function currentNewsId(){const hash=location.hash.match(/^#\/news\/([^/?#]+)/);if(hash)return decodeURIComponent(hash[1]);if(location.hash&&location.hash!=='#/')return null;const path=location.pathname.match(/^\/news\/([^/]+)\/?$/);return path?decodeURIComponent(path[1]):null}
export function newsCard(news){return `<a class="news-card" href="${newsUrl(news.id)}" aria-label="阅读：${escape(news.title)}"><span class="news-cover"><img onerror="this.onerror=null;this.src='${imageFallback(news.sport)}'" src="${news.cover}" alt="${escape(news.league)}赛场" loading="lazy"></span><span class="news-card-copy"><h3>${escape(news.title)}</h3><span class="news-card-meta"><span class="news-league">${escape(news.league)}</span><time datetime="${news.publishTime.replace(' ','T')}+08:00">${news.publishTime.slice(5)}</time></span></span></a>`}
export function newsHeadlines(){return `<aside class="home-headlines" aria-label="新闻头条"><div class="section-head"><h2>新闻头条</h2></div><div class="news-list">${newsItems.slice(0,6).map(newsCard).join('')}</div></aside>`}
export function newsDetail(id,{header,footer,homeLink}){const news=newsItems.find(item=>item.id===id);if(!news)return `${header()}<main class="news-page"><div class="news-not-found"><h1>新闻暂不可用</h1><p>该新闻不存在或已下线。</p><a href="${homeLink}">返回头条 ›</a></div></main>${footer()}`;
const recommendations=newsItems.filter(item=>item.id!==id).sort((a,b)=>((b.league===news.league?2:b.sport===news.sport?1:0)-(a.league===news.league?2:a.sport===news.sport?1:0))).slice(0,6);
return `${header()}<main class="news-page"><a class="news-back" href="${homeLink}">‹ 返回头条</a><div class="news-detail-layout"><article class="news-article"><span class="news-league">${escape(news.league)}</span><h1>${escape(news.title)}</h1><div class="news-article-meta"><span>作者：${escape(news.author)}</span><time datetime="${news.publishTime.replace(' ','T')}+08:00">发布时间：${news.publishTime}</time><span>阅读：${news.views.toLocaleString('zh-CN')}</span></div><div class="news-body">${news.content.map(block=>block.type==='image'?`<figure><img onerror="this.onerror=null;this.src='${imageFallback(news.sport)}'" src="${news.contentImages[block.imageIndex]}" alt="${escape(block.caption)}"><figcaption>${escape(block.caption)}</figcaption></figure>`:block.type==='heading'?`<h2>${escape(block.text)}</h2>`:`<p>${escape(block.text)}</p>`).join('')}</div></article><aside class="news-recommend"><div class="section-head"><h2>其他推荐新闻</h2></div><div class="news-list">${recommendations.map(newsCard).join('')}</div></aside></div></main>${footer()}`}

export const newsLeagues = ['全部','英超','西甲','意甲','德甲','法甲','欧冠','NBA','CBA'];
export function newsPage({header,footer}) {
  const requested = new URLSearchParams(location.hash.split('?')[1] || '').get('league');
  const league = newsLeagues.includes(requested) ? requested : '全部';
  const items = newsItems.filter(item => league === '全部' || item.league === league).sort((a,b) => b.publishTime.localeCompare(a.publishTime));
  return `${header()}<main class="news-page news-index"><nav class="news-league-filter" aria-label="新闻联赛筛选">${newsLeagues.map(name => `<a href="#/news${name === '全部' ? '' : `?league=${encodeURIComponent(name)}`}" class="${name === league ? 'selected' : ''}" ${name === league ? 'aria-current="true"' : ''}>${name}</a>`).join('')}</nav><div class="news-index-heading"><h2>${league === '全部' ? '全部新闻' : `${escape(league)}新闻`}</h2></div><section class="news-feed" aria-label="新闻列表">${items.map(news => `<a class="news-feed-card" href="#/news/${encodeURIComponent(news.id)}"><span class="news-league">${escape(news.league)}</span><h2>${escape(news.title)}</h2><p class="news-summary">${escape(news.summary || news.content.find(block => block.type === 'paragraph').text)}</p><div class="news-feed-meta"><span>${escape(news.author)}</span><time datetime="${news.publishTime.replace(' ','T')}+08:00">${news.publishTime}</time><span>浏览 ${news.views.toLocaleString('zh-CN')}</span></div></a>`).join('')}</section></main>${footer()}`;
}
